micronaut:
    application:
        name: cqrslight-micronaut
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:public"